version: '3.8'
name: youtube_download

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
     - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}



volumes:
  postgres-data:
